#!/bin/sh

# Copyright (C) 2012-2016 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
self=`basename $0`

if ! test -d "$COSMOS_REPO/.git"; then
    test -z "$COSMOS_VERBOSE" || \
	echo "$self: ignoring non-git repository: $COSMOS_REPO" 1>&2
    exit 0
fi

if test -n "$COSMOS_VERBOSE"; then
    GIT_PULL_ARGS=" -v"
    GIT_CHECKOUT_ARGS=
else
    GIT_PULL_ARGS=" -q"
    GIT_CHECKOUT_ARGS=" -q"
fi
if test -n "$COSMOS_DRY_RUN$COSMOS_DRY_TASKS"; then
    dry=echo
else
    dry=
fi

test -z "$COSMOS_VERBOSE" || \
    echo "$self: invoking git: cd \"$COSMOS_REPO\" && git checkout $GIT_CHECKOUT_ARGS master && git pull $GIT_PULL_ARGS"

cd "$COSMOS_REPO" && \
    $dry git checkout $GIT_CHECKOUT_ARGS master && \
    $dry git reset --hard && \
    $dry git pull $GIT_PULL_ARGS
