#!/bin/sh

# Copyright (C) 2012-2014 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
self=`basename $0`

if test -n "$COSMOS_VERBOSE"; then
    RSYNC_ARGS=" -v"
fi
if test -n "$COSMOS_DRY_TASKS"; then
    RSYNC_ARGS="$RSYNC_ARGS --dry-run"
fi
if test -n "$COSMOS_DRY_RUN"; then
    dry=echo
else
    dry=
fi

RSYNC_CMD="rsync$RSYNC_ARGS --archive --delete"
RSYNC="$RSYNC_CMD"

# FIXME: There is no way to escape a : in a path.  This is similar to
# PATH.  I currently don't see any way to resolve this limitation in
# POSIX-compatible shell script.

oIFS=$IFS
IFS=:
set -- $COSMOS_REPO_MODELS
IFS=$oIFS

test -z "$COSMOS_VERBOSE" \
    || echo "$self: invoking $RSYNC $@ \"$COSMOS_MODEL\""

$dry $RSYNC "$@" "$COSMOS_MODEL"
