#!/bin/sh

# Copyright (C) 2012-2016 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
self=`basename $0`

repo="$1"

case "$repo" in
    ssh://*)
	break
	;;
    https://*)
        break
        ;;
    git://*)
	break
	;;
    *)
	test -z "$COSMOS_VERBOSE" || \
	    echo "$self: ignoring non-git repository: $repo" 1>&2
	exit 0
	;;
esac

if test -n "$COSMOS_DRY_RUN$COSMOS_DRY_TASKS"; then
    test -z "$COSMOS_VERBOSE" || echo "$self: invoking (dry-run) cloning"
    echo "git clone \"$repo\" \"$COSMOS_REPO\""
else
    test -z "$COSMOS_VERBOSE" || echo "$self: cloning $repo into $COSMOS_REPO"
    git clone "$repo" "$COSMOS_REPO"
fi
